// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsyqycsezaqrlzqykfec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzeXF5Y3NlemFxcmx6cXlrZmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjg3MDksImV4cCI6MjA2NDYwNDcwOX0.EIJuJOzLTiqaCi6gsrwi6GomrJ73HphsJdo35yLMPgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);